language: elixir
elixir:
  - 1.9.1
script:
  - mix test
  - mix credo --strict
deploy:
  provider: heroku
  app: enigmatic-stream-8949
  api_key:
    secure: lXkd5mQtmi6Cq9Z5G91QdxWEIWVxytE8Iose3rPkZfHKqlhEht5Ajy9fUWYf0oFi8gs3DB9+bSEnUsbyTUjHITaCvGfsxdltqWsTCsmxjUuyCJfZ33WPJ/DcR9KJUFzrBHOvEv9zva244lqMV2dEMe6xXuLYIo/ywAwzZUh3jOk2s9pe+sW0xcx0CwCU4oDNBDgdhUB+jYTlgI9F6RdjdT6eNn8jTADF+Y+KzWBNHVm0ihIfu8/slwGcg49rVZ8oFcgO/O+LnVD1DvLMQ5hVYEEXVwnjLClgPnMYQOVyTzdwRjesQr43O2hEfQDVVFNoTKWQjzin3j42JBCHp0irKJ2hLVvlzrmFdP7xeG+nQb0SqI/4/hj11xicfWQCDRb5pMbEOp18rliIG56dT5h7IrbK6Ft4OkoCrP2QhcQHGve/skNh+corn2bF0yznfsu/fAmqddBK9ddTksOfhoSIp+HB27l/u+F/SPB/F5h+bMAqUhtRBNswiFpX+dJGc8qeI0B3EOtQJ/WnpWf1fFmQ7bW1RKaIrXU4izZxI6p4XTBye8TXG4jX2exPpiIgIiP9Mpe5QIPvb0zdvzYx38IjbPuIwWz1SzVhmPTahiwg1H5LeyY2Xp3L8AJhOt0NzHPYYd7tbwyng3jd06vNHHuzPY4tEcO1BNOCmikI+z4OUiY=
