name: Elixir CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: elixir:latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Build
      run: mix compile
    - name: Lint
      run: mix credo --strict
    - name: Run Tests
      run: mix test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v1
    - name: Deploy to Heroku
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        HEROKU_APP_NAME: "enigmatic-stream-8949"
        GITHUB_COMMIT: ${{ github.sha }}
      run: git push --force https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git $GITHUB_COMMIT:master
